# Generated by Django 5.2 on 2025-05-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аты-жөні')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон нөмірі')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жіберілген уақыты')),
            ],
        ),
    ]
